spring:
  application:
    name: Shopping Mall API

  # Postgresql Database 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ian
    password:
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

# 로깅 설정
logging:
  level:
    root: INFO
    com.codeit: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 서버 설정
server:
  port: 8080

# actuator info 설정
# POST loggers/com.codeit body:{"configuredLevel":"INFO"} 로 설정 바꾸기 가능
info:
  app:
    name: My Shopping Mall
    description: E-commerce platform for fashion items
    version: 1.0.0
    encoding: UTF-8
    java-version: 17

  company:
    name: MyCompany
    email: support@mycompany.com
    website: https://mycompany.com

  team:
    developer: Backend Team
    manager: John Doe
    contact: backend-team@mycompany.com

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, env # *
      base-path: /management  #actuator->management 로 경로 변경
  endpoint:
    health:
      show-details: always #개발 환경에서는 always, 운영에서는 when-authorized
  info:
    env:
      enabled: true
  server:
    port: 9090 # Actuator 전용 포트 (방화벽으로 막음)